---
ID: "7ac74676-6490-40bf-b525-1331b4554c9a"
Parent: "82a8137f-308b-4628-a4ee-9a35d9a1b0bf"
Template: "82a8137f-308b-4628-a4ee-9a35d9a1b0bf"
Path: /sitecore/templates/Project/teamhorizon2024/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240302T093332Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\julius.angwenyi@accenture.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\julius.angwenyi@accenture.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ffb33d9f-adca-4943-981a-48a5c2ab7efd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\julius.angwenyi@accenture.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T093332Z
